// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const edge = require('selenium-webdriver/edge');

const options = new edge.Options();
options.addArguments('headless');

describe('suitcase', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('MicrosoftEdge').setEdgeOptions(options).build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('suitcase', async function() {
    // Test name: suitcase
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1048x824 | 
    await driver.manage().window().setRect({ width: 1048, height: 824 })
    // 3 | click | css=.carousel-control-prev-icon | 
    await driver.findElement(By.css(".carousel-control-prev-icon")).click()
    // 4 | click | css=.carousel-control-prev-icon | 
    await driver.findElement(By.css(".carousel-control-prev-icon")).click()
    // 5 | click | linkText=Mis Rutinas | 
    await driver.findElement(By.linkText("Mis Rutinas")).click()
  })
})
