// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const chrome = require('selenium-webdriver/chrome')

const options = new chrome.Options();
options.addArguments('headless');


describe('suitcase', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').setChromeOptions(options).build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('suitcase', async function() {
    // Test name: suitcase
    await driver.manage().setTimeouts( { implicit: 10000 } );
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1054x824 | 
    let webElement = driver.findElement(By.id("myDynamicElement"));
    await driver.manage().window().setRect({ width: 1054, height: 824 })
    // 3 | click | linkText=Mis Rutinas | 
    await driver.findElement(By.linkText("Mis Rutinas")).click()
    // 4 | click | css=.add-button | 
    await driver.findElement(By.css(".add-button")).click()
    // 5 | click | id=name | 
    await driver.findElement(By.id("name")).click()
    // 6 | type | id=name | nueva_rutina
    await driver.findElement(By.id("name")).sendKeys("nueva_rutina")
    // 7 | click | id=grupo | 
    await driver.findElement(By.id("grupo")).click()
    // 8 | type | id=grupo | todo
    await driver.findElement(By.id("grupo")).sendKeys("todo")
    // 9 | click | css=.btn-primary | 
    await driver.findElement(By.css(".btn-primary")).click()
    // 10 | click | css=tr:nth-child(11) .btn-success > .MuiSvgIcon-root | 
    await driver.findElement(By.css("tr:nth-child(11) .btn-success > .MuiSvgIcon-root")).click()
    // 11 | click | css=.add-button | 
    await driver.findElement(By.css(".add-button")).click()
    // 12 | mouseOver | css=.add-button | 
    {
      const element = await driver.findElement(By.css(".add-button"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 13 | mouseOut | css=.add-button | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 14 | click | css=form | 
    await driver.findElement(By.css("form")).click()
    // 15 | click | id=name | 
    await driver.findElement(By.id("name")).click()
    // 16 | type | id=name | nuevo_ejercicio
    await driver.findElement(By.id("name")).sendKeys("nuevo_ejercicio")
    // 17 | click | id=reps | 
    await driver.findElement(By.id("reps")).click()
    // 18 | type | id=reps | 10
    await driver.findElement(By.id("reps")).sendKeys("10")
    // 19 | click | id=duration | 
    await driver.findElement(By.id("duration")).click()
    // 20 | type | id=duration | 3 series
    await driver.findElement(By.id("duration")).sendKeys("3 series")
    // 21 | click | id=peso | 
    await driver.findElement(By.id("peso")).click()
    // 22 | type | id=peso | 69
    await driver.findElement(By.id("peso")).sendKeys("69")
    // 23 | click | css=.btn-primary | 
    await driver.findElement(By.css(".btn-primary")).click()
    // 24 | click | linkText=Mis Rutinas | 
    await driver.findElement(By.linkText("Mis Rutinas")).click()
    // 25 | click | css=tr:nth-child(11) .btn-warning | 
    await driver.findElement(By.css("tr:nth-child(11) .btn-warning")).click()
    // 26 | click | id=grupo | 
    await driver.findElement(By.id("grupo")).click()
    // 27 | type | id=grupo | todo_elcuerpo
    await driver.findElement(By.id("grupo")).sendKeys("todo_elcuerpo")
    // 28 | click | css=.btn-primary | 
    await driver.findElement(By.css(".btn-primary")).click()
    // 29 | click | css=tr:nth-child(11) .btn-success > .MuiSvgIcon-root | 
    await driver.findElement(By.css("tr:nth-child(11) .btn-success > .MuiSvgIcon-root")).click()
    // 30 | runScript | window.scrollTo(0,0) | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 31 | click | css=.btn-danger > .MuiSvgIcon-root | 
    await driver.findElement(By.css(".btn-danger > .MuiSvgIcon-root")).click()
    // 32 | mouseOver | css=.btn-danger > .MuiSvgIcon-root | 
    {
      const element = await driver.findElement(By.css(".btn-danger > .MuiSvgIcon-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 33 | mouseOut | css=.btn-danger > .MuiSvgIcon-root | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 34 | click | css=.btn-danger:nth-child(1) | 
    await driver.findElement(By.css(".btn-danger:nth-child(1)")).click()
    // 35 | click | linkText=Mis Rutinas | 
    await driver.findElement(By.linkText("Mis Rutinas")).click()
    // 36 | click | css=tr:nth-child(11) .btn-danger > .MuiSvgIcon-root | 
    await driver.findElement(By.css("tr:nth-child(11) .btn-danger > .MuiSvgIcon-root")).click()
    // 37 | mouseOver | css=.btn-danger:nth-child(1) | 
    {
      const element = await driver.findElement(By.css(".btn-danger:nth-child(1)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 38 | mouseOut | css=tr:nth-child(11) .btn-danger > .MuiSvgIcon-root | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 39 | click | css=.btn-danger:nth-child(1) | 
    await driver.findElement(By.css(".btn-danger:nth-child(1)")).click()
  })
})
